#!/bin/sh
all = (${@//[!0-9]/})
[ "${#all[@]}" != "8" ] && {
        echo "Usage : "
        echo "${0##*/} ip.ip.ip.ip/mask.mask.mask.mask"
        exit 1
}

get_addr() {
        if ["$1" = "-b"]; then
                op='|'; op1=



}
